config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'

  resources :users
  resources :routines, only: [:create, :show]
  resources :exercises, only: [:show]
  resources :likes, only: [:index]
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :routines
	belongs_to :users, through: :routines
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :users
	belongs_to :routines

end

app/models/routine.rb
class Routine < ActiveRecord::Base
	belongs_to :users
	has_many :exercises 
	has_many :likes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
	has_many :routines
	has_many :exercises, through: :routines
	has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

	def show
	end
	
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

	def index
	end
	
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :authenticate_user!

	def show
	end

	def create
	end

	def new
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
		else
			render 'edit'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :age, :weight, :goal)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/exercises/show.html.erb
exercise name: push-up
youtube instructional video below

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waywo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :get %> | 
    <%= link_to "Home", root_path %> |
    <%= link_to "My Likes", likes_path %> |
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %>
  <% end %>
  <section>
<hr style="border: 1px outset #08088A;">
  </section>
<%= yield %>

</body>
</html>

app/views/likes/index.html.erb
all my liked routines

app/views/routines/new.html.erb
type of workout:
	endurance
	strength
	tone
	stretch 

length of workout:
	~15 minutes
	~30 minutes
	~45 minutes
	~1 hour

GENERATE BUTTON

app/views/routines/show.html.erb
workout name

exercise 1 #=> can click on exercise and will open a new tab to a page with the workout name as a title and a youtube video of how to do the workout embedded below
exercise 2
exercise 3
exercise 4
etc...

app/views/users/_form.html.erb
<% form_for(@user) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :age %>
<%= f.text_field :age %>
<%= f.label :weight %>
<%= f.text_field :weight %>
<%= f.label :goal %>
<%= f.text_field :goal %>
<%= f.submit "Save Changes and get Shredding" %>
<% end %>

app/views/users/edit.html.erb
<h2> Edit Profile </h2>
<%= render 'form' %>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>
<%= link_to 'edit', edit_user_path(@user) %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>